# Generated by Django 3.1.7 on 2021-07-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categoria_producto_subcategoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='subCategoria',
            new_name='subcategoria',
        ),
    ]
